name: main CI

on: [push, pull_request]

jobs:
  build:
    name: UnityGame
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Support windows, macos, linux
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Enable large file system (lfs)
          lfs: true
      
      # TODO: Cache

      # # TODO: Test
      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v2
      #   # TODO: needs env here for UNITY_LICENSE
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
          
      # Build
      # TODO: add UNITY_LICENSE (all 3 variables to the secrets)
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

